### ISSUE TITLE
Error when running "python run.py -e prototype_10" for Dendrites project

### ISSUE THREAD

**Issue by LeKo0** [numenta/nupic.research#637]
Hi,

I made no modification to the code and have followed all the instructions in the README.txt but I get the following error message :
```
(numenta) [leko@leko-pc permutedMNIST]$ python run.py -e prototype_10 --run_without_ray_tune True
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    run(config)
  File "/home/leko/Documents/nupic.research/src/nupic/research/frameworks/vernon/run.py", line 171, in run
    ctx_worker = mp.spawn(worker, args=(world_size, dist_url, config, queue),
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/leko/anaconda3/envs/numenta/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f2e71df1940>: attribute lookup <lambda> on experiments.prototype failed
```
Any idea what's happening?

**Comment by zhaoyaqia** [comment]
> 

Hi,I have a problem.
ImportError: cannot import name '_TuneFunctionDecoder' from 'ray.tune.trial_runner' (E:\anaconda3\envs\dendrites\lib\site-packages\ray\tune\trial_runner.py)
Do you know how to solve it? Thanks for your help.

**Comment by zhaoyaqia** [comment]
Have you solved your problem? I have the same problem as you, okay? I want to know how to solve it.

**Comment by subutai** [comment]
The continual learning experiments should be run from the following repository, as this is a stable version of our implementation:

https://github.com/numenta/htmpapers/tree/master/biorxiv/going_beyond_the_point_neuron

We had provided a link to an unstable version, and that has been updated now. Sorry about that! If you follow the instructions in the README file in the link above, you should have no errors. Also, please don't use the flag `run_without_ray_tune`, just simply run `python run.py -e prototype_10`.

**Comment by zhaoyaqia** [comment]
> The continual learning experiments should be run from the following repository, as this is a stable version of our implementation:
> 
> https://github.com/numenta/htmpapers/tree/master/biorxiv/going_beyond_the_point_neuron
> 
> We had provided a link to an unstable version, and that has been updated now. Sorry about that! If you follow the instructions in the README file in the link above, you should have no errors. Also, please don't use the flag `run_without_ray_tune`, just simply run `python run.py -e prototype_10`.

Firstly,ray==0.8.7 doesn't work on my computer. So I update it to ray==1.11.0.
When I run 'python run.py -e prototype_10' , it also failed.
And it prints:"ImportError: cannot import name '_TuneFunctionDecoder' from 'ray.tune.trial_runner' (E:\anaconda3\envs\nupic.research\lib\site-packages\ray\tune\trial_runner.py)
I need your help. Thanks for your reply.
